version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      npm-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      npm-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions-minor-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch
      github-actions-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
